# Generated by Django 2.1 on 2019-09-29 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_finished']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_finished',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 9, 29, 19, 22, 43, 831658, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
